### ISSUE TITLE
기술 스택 결정

### ISSUE THREAD

**Issue by RanolP** [daily-boj/homepage#1]
- Rust!!!!!!!!!!
- yew

**Comment by RanolP** [comment]
Pages로 배포하는 데에 GitHub Actions 사용하기

**Comment by kiwiyou** [comment]
@RanolP 그러면 커스텀 이미지를 만들어야 하는데 레퍼런스가...

**Comment by RanolP** [comment]
https://github.com/Team-StarGarden/darakbang-protocol-docs/
요기서 actions 갖고 배포해본 경험이 잇서요

**Comment by RanolP** [comment]
Actions 대충 설정 완료. daily-boj.github.io가 아니라서 조금 슬픔. CNAME을 추후에 붙여보는 걸로

**Comment by RanolP** [comment]
당장은 이 기술 스택으로 삽질을 해보는 걸로
